# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.auditor_pb2 as auditor__pb2


class DocumentAuditorStub(object):
    """--- 鏈嶅姟瀹氫箟 ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/ParseDocument',
                request_serializer=auditor__pb2.ParseRequest.SerializeToString,
                response_deserializer=auditor__pb2.ParsedData.FromString,
                )
        self.AuditRules = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/AuditRules',
                request_serializer=auditor__pb2.AuditRequest.SerializeToString,
                response_deserializer=auditor__pb2.AuditResponse.FromString,
                )
        self.AnalyzeSemantics = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/AnalyzeSemantics',
                request_serializer=auditor__pb2.SemanticRequest.SerializeToString,
                response_deserializer=auditor__pb2.AuditResponse.FromString,
                )
        self.InjectAnnotations = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/InjectAnnotations',
                request_serializer=auditor__pb2.InjectRequest.SerializeToString,
                response_deserializer=auditor__pb2.InjectResponse.FromString,
                )


class DocumentAuditorServicer(object):
    """--- 鏈嶅姟瀹氫箟 ---

    """

    def ParseDocument(self, request, context):
        """鎴愬憳 A (Rust): 瑙ｆ瀽鏂囨。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditRules(self, request, context):
        """鎴愬憳 B (Java): 鎵ц鏍煎紡涓庤鍒欏鏌?        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSemantics(self, request, context):
        """鎴愬憳 C (Python): 璇箟涓?AI 鏅鸿兘瀹℃煡
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InjectAnnotations(self, request, context):
        """鍙€夛細鍐欏洖鎵规敞鍚庣殑鏂囨。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentAuditorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=auditor__pb2.ParseRequest.FromString,
                    response_serializer=auditor__pb2.ParsedData.SerializeToString,
            ),
            'AuditRules': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditRules,
                    request_deserializer=auditor__pb2.AuditRequest.FromString,
                    response_serializer=auditor__pb2.AuditResponse.SerializeToString,
            ),
            'AnalyzeSemantics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSemantics,
                    request_deserializer=auditor__pb2.SemanticRequest.FromString,
                    response_serializer=auditor__pb2.AuditResponse.SerializeToString,
            ),
            'InjectAnnotations': grpc.unary_unary_rpc_method_handler(
                    servicer.InjectAnnotations,
                    request_deserializer=auditor__pb2.InjectRequest.FromString,
                    response_serializer=auditor__pb2.InjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'academic.auditor.DocumentAuditor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocumentAuditor(object):
    """--- 鏈嶅姟瀹氫箟 ---

    """

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/academic.auditor.DocumentAuditor/ParseDocument',
            auditor__pb2.ParseRequest.SerializeToString,
            auditor__pb2.ParsedData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AuditRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/academic.auditor.DocumentAuditor/AuditRules',
            auditor__pb2.AuditRequest.SerializeToString,
            auditor__pb2.AuditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeSemantics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/academic.auditor.DocumentAuditor/AnalyzeSemantics',
            auditor__pb2.SemanticRequest.SerializeToString,
            auditor__pb2.AuditResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InjectAnnotations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/academic.auditor.DocumentAuditor/InjectAnnotations',
            auditor__pb2.InjectRequest.SerializeToString,
            auditor__pb2.InjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
