// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.33.4
// source: auditor.proto

package auditorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocumentAuditorClient is the client API for DocumentAuditor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentAuditorClient interface {
	// 成员 A (Rust): 解析文档
	ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParsedData, error)
	// 成员 B (Java): 执行格式与规则审查
	AuditRules(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error)
	// 成员 C (Python): 语义与 AI 智能审查
	AnalyzeSemantics(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*AuditResponse, error)
	// 可选：写回批注后的文档
	InjectAnnotations(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error)
}

type documentAuditorClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentAuditorClient(cc grpc.ClientConnInterface) DocumentAuditorClient {
	return &documentAuditorClient{cc}
}

func (c *documentAuditorClient) ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParsedData, error) {
	out := new(ParsedData)
	err := c.cc.Invoke(ctx, "/academic.auditor.DocumentAuditor/ParseDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentAuditorClient) AuditRules(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, "/academic.auditor.DocumentAuditor/AuditRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentAuditorClient) AnalyzeSemantics(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, "/academic.auditor.DocumentAuditor/AnalyzeSemantics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentAuditorClient) InjectAnnotations(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error) {
	out := new(InjectResponse)
	err := c.cc.Invoke(ctx, "/academic.auditor.DocumentAuditor/InjectAnnotations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentAuditorServer is the server API for DocumentAuditor service.
// All implementations must embed UnimplementedDocumentAuditorServer
// for forward compatibility
type DocumentAuditorServer interface {
	// 成员 A (Rust): 解析文档
	ParseDocument(context.Context, *ParseRequest) (*ParsedData, error)
	// 成员 B (Java): 执行格式与规则审查
	AuditRules(context.Context, *AuditRequest) (*AuditResponse, error)
	// 成员 C (Python): 语义与 AI 智能审查
	AnalyzeSemantics(context.Context, *SemanticRequest) (*AuditResponse, error)
	// 可选：写回批注后的文档
	InjectAnnotations(context.Context, *InjectRequest) (*InjectResponse, error)
	mustEmbedUnimplementedDocumentAuditorServer()
}

// UnimplementedDocumentAuditorServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentAuditorServer struct {
}

func (UnimplementedDocumentAuditorServer) ParseDocument(context.Context, *ParseRequest) (*ParsedData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedDocumentAuditorServer) AuditRules(context.Context, *AuditRequest) (*AuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditRules not implemented")
}
func (UnimplementedDocumentAuditorServer) AnalyzeSemantics(context.Context, *SemanticRequest) (*AuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSemantics not implemented")
}
func (UnimplementedDocumentAuditorServer) InjectAnnotations(context.Context, *InjectRequest) (*InjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectAnnotations not implemented")
}
func (UnimplementedDocumentAuditorServer) mustEmbedUnimplementedDocumentAuditorServer() {}

// UnsafeDocumentAuditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentAuditorServer will
// result in compilation errors.
type UnsafeDocumentAuditorServer interface {
	mustEmbedUnimplementedDocumentAuditorServer()
}

func RegisterDocumentAuditorServer(s grpc.ServiceRegistrar, srv DocumentAuditorServer) {
	s.RegisterService(&DocumentAuditor_ServiceDesc, srv)
}

func _DocumentAuditor_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.auditor.DocumentAuditor/ParseDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).ParseDocument(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentAuditor_AuditRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).AuditRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.auditor.DocumentAuditor/AuditRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).AuditRules(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentAuditor_AnalyzeSemantics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).AnalyzeSemantics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.auditor.DocumentAuditor/AnalyzeSemantics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).AnalyzeSemantics(ctx, req.(*SemanticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentAuditor_InjectAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).InjectAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/academic.auditor.DocumentAuditor/InjectAnnotations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).InjectAnnotations(ctx, req.(*InjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentAuditor_ServiceDesc is the grpc.ServiceDesc for DocumentAuditor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentAuditor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.auditor.DocumentAuditor",
	HandlerType: (*DocumentAuditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _DocumentAuditor_ParseDocument_Handler,
		},
		{
			MethodName: "AuditRules",
			Handler:    _DocumentAuditor_AuditRules_Handler,
		},
		{
			MethodName: "AnalyzeSemantics",
			Handler:    _DocumentAuditor_AnalyzeSemantics_Handler,
		},
		{
			MethodName: "InjectAnnotations",
			Handler:    _DocumentAuditor_InjectAnnotations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auditor.proto",
}
