// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: shared/protos/auditor.proto

package auditorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_LOW      Severity = 1
	Severity_MEDIUM   Severity = 2
	Severity_HIGH     Severity = 3
	Severity_CRITICAL Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_protos_auditor_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_shared_protos_auditor_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{0}
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`             // 文档在共享存储中的路径
	TemplateType  string                 `protobuf:"bytes,2,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"` // 例如: "GB/T7714", "APA"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_shared_protos_auditor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ParseRequest) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

type ParsedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Metadata      *DocumentMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Sections      []*Section             `protobuf:"bytes,3,rep,name=sections,proto3" json:"sections,omitempty"`
	References    []*Reference           `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedData) Reset() {
	*x = ParsedData{}
	mi := &file_shared_protos_auditor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedData) ProtoMessage() {}

func (x *ParsedData) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedData.ProtoReflect.Descriptor instead.
func (*ParsedData) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedData) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ParsedData) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ParsedData) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *ParsedData) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

type DocumentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	PageCount     int32                  `protobuf:"varint,2,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	MarginTop     float32                `protobuf:"fixed32,3,opt,name=margin_top,json=marginTop,proto3" json:"margin_top,omitempty"`
	MarginBottom  float32                `protobuf:"fixed32,4,opt,name=margin_bottom,json=marginBottom,proto3" json:"margin_bottom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_shared_protos_auditor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentMetadata) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentMetadata) GetMarginTop() float32 {
	if x != nil {
		return x.MarginTop
	}
	return 0
}

func (x *DocumentMetadata) GetMarginBottom() float32 {
	if x != nil {
		return x.MarginBottom
	}
	return 0
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int32                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`    // "heading", "paragraph", "table", "figure"
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"` // 标题层级，0为正文
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Props         map[string]string      `protobuf:"bytes,5,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {"font": "SimSun", "size": "12pt", "indent": "2"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_shared_protos_auditor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{3}
}

func (x *Section) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *Section) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Section) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Section) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Section) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"` // 例如 "[1]"
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	IsValidFormat bool                   `protobuf:"varint,3,opt,name=is_valid_format,json=isValidFormat,proto3" json:"is_valid_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_shared_protos_auditor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{4}
}

func (x *Reference) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *Reference) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *Reference) GetIsValidFormat() bool {
	if x != nil {
		return x.IsValidFormat
	}
	return false
}

type AuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *ParsedData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TargetRuleSet string                 `protobuf:"bytes,2,opt,name=target_rule_set,json=targetRuleSet,proto3" json:"target_rule_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_shared_protos_auditor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{5}
}

func (x *AuditRequest) GetData() *ParsedData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuditRequest) GetTargetRuleSet() string {
	if x != nil {
		return x.TargetRuleSet
	}
	return ""
}

type SemanticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,2,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // 例如 "qwen-2.5-72b"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticRequest) Reset() {
	*x = SemanticRequest{}
	mi := &file_shared_protos_auditor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticRequest) ProtoMessage() {}

func (x *SemanticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticRequest.ProtoReflect.Descriptor instead.
func (*SemanticRequest) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{6}
}

func (x *SemanticRequest) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *SemanticRequest) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*Issue               `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	ScoreImpact   float32                `protobuf:"fixed32,2,opt,name=score_impact,json=scoreImpact,proto3" json:"score_impact,omitempty"` // 该模块发现的扣分项总计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_shared_protos_auditor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{7}
}

func (x *AuditResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *AuditResponse) GetScoreImpact() float32 {
	if x != nil {
		return x.ScoreImpact
	}
	return 0
}

// 将批注写回文档
type InjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"` // 原始文档路径
	Issues        []*Issue               `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`                     // 要写回的批注（含位置/严重度等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectRequest) Reset() {
	*x = InjectRequest{}
	mi := &file_shared_protos_auditor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectRequest) ProtoMessage() {}

func (x *InjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectRequest.ProtoReflect.Descriptor instead.
func (*InjectRequest) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{8}
}

func (x *InjectRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *InjectRequest) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type InjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnnotatedPath string                 `protobuf:"bytes,1,opt,name=annotated_path,json=annotatedPath,proto3" json:"annotated_path,omitempty"` // 生成的批注文档路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectResponse) Reset() {
	*x = InjectResponse{}
	mi := &file_shared_protos_auditor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectResponse) ProtoMessage() {}

func (x *InjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectResponse.ProtoReflect.Descriptor instead.
func (*InjectResponse) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{9}
}

func (x *InjectResponse) GetAnnotatedPath() string {
	if x != nil {
		return x.AnnotatedPath
	}
	return ""
}

type Issue struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Code            string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                             // 错误代码，如 "ERR_FONT_001"
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                       // 给用户的错误描述
	SectionId       int32                  `protobuf:"varint,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"` // 关联的段落 ID
	Severity        Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=academic.auditor.Severity" json:"severity,omitempty"`
	Suggestion      string                 `protobuf:"bytes,5,opt,name=suggestion,proto3" json:"suggestion,omitempty"`                                  // 修改建议
	OriginalSnippet string                 `protobuf:"bytes,6,opt,name=original_snippet,json=originalSnippet,proto3" json:"original_snippet,omitempty"` // 原始错误文本片段
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_shared_protos_auditor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_shared_protos_auditor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_shared_protos_auditor_proto_rawDescGZIP(), []int{10}
}

func (x *Issue) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Issue) GetSectionId() int32 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *Issue) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

func (x *Issue) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *Issue) GetOriginalSnippet() string {
	if x != nil {
		return x.OriginalSnippet
	}
	return ""
}

var File_shared_protos_auditor_proto protoreflect.FileDescriptor

const file_shared_protos_auditor_proto_rawDesc = "" +
	"\n" +
	"\x1bshared/protos/auditor.proto\x12\x10academic.auditor\"P\n" +
	"\fParseRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12#\n" +
	"\rtemplate_type\x18\x02 \x01(\tR\ftemplateType\"\xd7\x01\n" +
	"\n" +
	"ParsedData\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\".academic.auditor.DocumentMetadataR\bmetadata\x125\n" +
	"\bsections\x18\x03 \x03(\v2\x19.academic.auditor.SectionR\bsections\x12;\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\x1b.academic.auditor.ReferenceR\n" +
	"references\"\x8b\x01\n" +
	"\x10DocumentMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"page_count\x18\x02 \x01(\x05R\tpageCount\x12\x1d\n" +
	"\n" +
	"margin_top\x18\x03 \x01(\x02R\tmarginTop\x12#\n" +
	"\rmargin_bottom\x18\x04 \x01(\x02R\fmarginBottom\"\xdc\x01\n" +
	"\aSection\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x05R\tsectionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12:\n" +
	"\x05props\x18\x05 \x03(\v2$.academic.auditor.Section.PropsEntryR\x05props\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\tReference\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x12&\n" +
	"\x0fis_valid_format\x18\x03 \x01(\bR\risValidFormat\"h\n" +
	"\fAuditRequest\x120\n" +
	"\x04data\x18\x01 \x01(\v2\x1c.academic.auditor.ParsedDataR\x04data\x12&\n" +
	"\x0ftarget_rule_set\x18\x02 \x01(\tR\rtargetRuleSet\"m\n" +
	"\x0fSemanticRequest\x125\n" +
	"\bsections\x18\x01 \x03(\v2\x19.academic.auditor.SectionR\bsections\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\"c\n" +
	"\rAuditResponse\x12/\n" +
	"\x06issues\x18\x01 \x03(\v2\x17.academic.auditor.IssueR\x06issues\x12!\n" +
	"\fscore_impact\x18\x02 \x01(\x02R\vscoreImpact\"]\n" +
	"\rInjectRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12/\n" +
	"\x06issues\x18\x02 \x03(\v2\x17.academic.auditor.IssueR\x06issues\"7\n" +
	"\x0eInjectResponse\x12%\n" +
	"\x0eannotated_path\x18\x01 \x01(\tR\rannotatedPath\"\xd7\x01\n" +
	"\x05Issue\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\x05R\tsectionId\x126\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1a.academic.auditor.SeverityR\bseverity\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x05 \x01(\tR\n" +
	"suggestion\x12)\n" +
	"\x10original_snippet\x18\x06 \x01(\tR\x0foriginalSnippet*A\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x042\xdf\x02\n" +
	"\x0fDocumentAuditor\x12M\n" +
	"\rParseDocument\x12\x1e.academic.auditor.ParseRequest\x1a\x1c.academic.auditor.ParsedData\x12M\n" +
	"\n" +
	"AuditRules\x12\x1e.academic.auditor.AuditRequest\x1a\x1f.academic.auditor.AuditResponse\x12V\n" +
	"\x10AnalyzeSemantics\x12!.academic.auditor.SemanticRequest\x1a\x1f.academic.auditor.AuditResponse\x12V\n" +
	"\x11InjectAnnotations\x12\x1f.academic.auditor.InjectRequest\x1a .academic.auditor.InjectResponseBU\n" +
	"\x10com.auditor.grpcB\fAuditorProtoP\x01Z1ai-auditor-core/shared/protos/auditorpb;auditorpbb\x06proto3"

var (
	file_shared_protos_auditor_proto_rawDescOnce sync.Once
	file_shared_protos_auditor_proto_rawDescData []byte
)

func file_shared_protos_auditor_proto_rawDescGZIP() []byte {
	file_shared_protos_auditor_proto_rawDescOnce.Do(func() {
		file_shared_protos_auditor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_protos_auditor_proto_rawDesc), len(file_shared_protos_auditor_proto_rawDesc)))
	})
	return file_shared_protos_auditor_proto_rawDescData
}

var file_shared_protos_auditor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_protos_auditor_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_shared_protos_auditor_proto_goTypes = []any{
	(Severity)(0),            // 0: academic.auditor.Severity
	(*ParseRequest)(nil),     // 1: academic.auditor.ParseRequest
	(*ParsedData)(nil),       // 2: academic.auditor.ParsedData
	(*DocumentMetadata)(nil), // 3: academic.auditor.DocumentMetadata
	(*Section)(nil),          // 4: academic.auditor.Section
	(*Reference)(nil),        // 5: academic.auditor.Reference
	(*AuditRequest)(nil),     // 6: academic.auditor.AuditRequest
	(*SemanticRequest)(nil),  // 7: academic.auditor.SemanticRequest
	(*AuditResponse)(nil),    // 8: academic.auditor.AuditResponse
	(*InjectRequest)(nil),    // 9: academic.auditor.InjectRequest
	(*InjectResponse)(nil),   // 10: academic.auditor.InjectResponse
	(*Issue)(nil),            // 11: academic.auditor.Issue
	nil,                      // 12: academic.auditor.Section.PropsEntry
}
var file_shared_protos_auditor_proto_depIdxs = []int32{
	3,  // 0: academic.auditor.ParsedData.metadata:type_name -> academic.auditor.DocumentMetadata
	4,  // 1: academic.auditor.ParsedData.sections:type_name -> academic.auditor.Section
	5,  // 2: academic.auditor.ParsedData.references:type_name -> academic.auditor.Reference
	12, // 3: academic.auditor.Section.props:type_name -> academic.auditor.Section.PropsEntry
	2,  // 4: academic.auditor.AuditRequest.data:type_name -> academic.auditor.ParsedData
	4,  // 5: academic.auditor.SemanticRequest.sections:type_name -> academic.auditor.Section
	11, // 6: academic.auditor.AuditResponse.issues:type_name -> academic.auditor.Issue
	11, // 7: academic.auditor.InjectRequest.issues:type_name -> academic.auditor.Issue
	0,  // 8: academic.auditor.Issue.severity:type_name -> academic.auditor.Severity
	1,  // 9: academic.auditor.DocumentAuditor.ParseDocument:input_type -> academic.auditor.ParseRequest
	6,  // 10: academic.auditor.DocumentAuditor.AuditRules:input_type -> academic.auditor.AuditRequest
	7,  // 11: academic.auditor.DocumentAuditor.AnalyzeSemantics:input_type -> academic.auditor.SemanticRequest
	9,  // 12: academic.auditor.DocumentAuditor.InjectAnnotations:input_type -> academic.auditor.InjectRequest
	2,  // 13: academic.auditor.DocumentAuditor.ParseDocument:output_type -> academic.auditor.ParsedData
	8,  // 14: academic.auditor.DocumentAuditor.AuditRules:output_type -> academic.auditor.AuditResponse
	8,  // 15: academic.auditor.DocumentAuditor.AnalyzeSemantics:output_type -> academic.auditor.AuditResponse
	10, // 16: academic.auditor.DocumentAuditor.InjectAnnotations:output_type -> academic.auditor.InjectResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shared_protos_auditor_proto_init() }
func file_shared_protos_auditor_proto_init() {
	if File_shared_protos_auditor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_protos_auditor_proto_rawDesc), len(file_shared_protos_auditor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_protos_auditor_proto_goTypes,
		DependencyIndexes: file_shared_protos_auditor_proto_depIdxs,
		EnumInfos:         file_shared_protos_auditor_proto_enumTypes,
		MessageInfos:      file_shared_protos_auditor_proto_msgTypes,
	}.Build()
	File_shared_protos_auditor_proto = out.File
	file_shared_protos_auditor_proto_goTypes = nil
	file_shared_protos_auditor_proto_depIdxs = nil
}
