# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import sys
from pathlib import Path

# Ensure sibling generated modules can be imported when this file is executed
# as a module (adds this directory to sys.path so `import auditor_pb2` works).
sys.path.insert(0, str(Path(__file__).resolve().parent))

import auditor_pb2 as auditor__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in auditor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentAuditorStub(object):
    """--- 服务定义 ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/ParseDocument',
                request_serializer=auditor__pb2.ParseRequest.SerializeToString,
                response_deserializer=auditor__pb2.ParsedData.FromString,
                _registered_method=True)
        self.AuditRules = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/AuditRules',
                request_serializer=auditor__pb2.AuditRequest.SerializeToString,
                response_deserializer=auditor__pb2.AuditResponse.FromString,
                _registered_method=True)
        self.AnalyzeSemantics = channel.unary_unary(
                '/academic.auditor.DocumentAuditor/AnalyzeSemantics',
                request_serializer=auditor__pb2.SemanticRequest.SerializeToString,
                response_deserializer=auditor__pb2.AuditResponse.FromString,
                _registered_method=True)


class DocumentAuditorServicer(object):
    """--- 服务定义 ---

    """

    def ParseDocument(self, request, context):
        """成员 A (Rust): 解析文档
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditRules(self, request, context):
        """成员 B (Java): 执行格式与规则审查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSemantics(self, request, context):
        """成员 C (Python): 语义与 AI 智能审查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentAuditorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=auditor__pb2.ParseRequest.FromString,
                    response_serializer=auditor__pb2.ParsedData.SerializeToString,
            ),
            'AuditRules': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditRules,
                    request_deserializer=auditor__pb2.AuditRequest.FromString,
                    response_serializer=auditor__pb2.AuditResponse.SerializeToString,
            ),
            'AnalyzeSemantics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSemantics,
                    request_deserializer=auditor__pb2.SemanticRequest.FromString,
                    response_serializer=auditor__pb2.AuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'academic.auditor.DocumentAuditor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('academic.auditor.DocumentAuditor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentAuditor(object):
    """--- 服务定义 ---

    """

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/academic.auditor.DocumentAuditor/ParseDocument',
            auditor__pb2.ParseRequest.SerializeToString,
            auditor__pb2.ParsedData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/academic.auditor.DocumentAuditor/AuditRules',
            auditor__pb2.AuditRequest.SerializeToString,
            auditor__pb2.AuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeSemantics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/academic.auditor.DocumentAuditor/AnalyzeSemantics',
            auditor__pb2.SemanticRequest.SerializeToString,
            auditor__pb2.AuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
