// This file is @generated by prost-build.
/// 文档段落/元素
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DocumentSection {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(enumeration = "ElementType", tag = "2")]
    pub r#type: i32,
    #[prost(string, tag = "3")]
    pub raw_text: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub formatting: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "5")]
    pub xml_path: ::prost::alloc::string::String,
}
/// 文档元数据
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DocumentMetadata {
    #[prost(int32, tag = "1")]
    pub total_elements: i32,
    #[prost(int32, tag = "2")]
    pub heading_count: i32,
    #[prost(int32, tag = "3")]
    pub table_count: i32,
}
/// 文档树节点
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SectionNode {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub level: u32,
    #[prost(string, tag = "4")]
    pub xml_path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub children: ::prost::alloc::vec::Vec<SectionItem>,
}
/// 节点项（子节或内容）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SectionItem {
    #[prost(oneof = "section_item::Item", tags = "1, 2")]
    pub item: ::core::option::Option<section_item::Item>,
}
/// Nested message and enum types in `SectionItem`.
pub mod section_item {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Item {
        #[prost(message, tag = "1")]
        Subsection(super::SectionNode),
        #[prost(message, tag = "2")]
        Content(super::DocumentSection),
    }
}
/// 完整文档树
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DocumentTree {
    #[prost(message, optional, tag = "1")]
    pub root: ::core::option::Option<SectionNode>,
    #[prost(message, optional, tag = "2")]
    pub metadata: ::core::option::Option<DocumentMetadata>,
}
/// 解析结果（主输出）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParsedData {
    #[prost(message, optional, tag = "1")]
    pub document_tree: ::core::option::Option<DocumentTree>,
}
/// 评论消息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Comment {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub paragraph_index: i32,
}
/// 解析文档请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseDocumentRequest {
    #[prost(string, tag = "1")]
    pub file_path: ::prost::alloc::string::String,
}
/// 解析文档响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseDocumentResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub parsed_data: ::core::option::Option<ParsedData>,
}
/// 注入评论请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InjectCommentsRequest {
    #[prost(string, tag = "1")]
    pub input_file_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub output_file_path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub comments: ::prost::alloc::vec::Vec<Comment>,
    #[prost(string, tag = "4")]
    pub author: ::prost::alloc::string::String,
}
/// 注入评论响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InjectCommentsResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub output_file_path: ::prost::alloc::string::String,
}
/// 元素类型枚举
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ElementType {
    Paragraph = 0,
    Heading = 1,
    Table = 2,
    Equation = 3,
}
impl ElementType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ElementType::Paragraph => "PARAGRAPH",
            ElementType::Heading => "HEADING",
            ElementType::Table => "TABLE",
            ElementType::Equation => "EQUATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PARAGRAPH" => Some(Self::Paragraph),
            "HEADING" => Some(Self::Heading),
            "TABLE" => Some(Self::Table),
            "EQUATION" => Some(Self::Equation),
            _ => None,
        }
    }
}
