// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: shared/protos/auditor.proto

package auditorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentAuditor_ParseDocument_FullMethodName     = "/academic.auditor.DocumentAuditor/ParseDocument"
	DocumentAuditor_AuditRules_FullMethodName        = "/academic.auditor.DocumentAuditor/AuditRules"
	DocumentAuditor_AnalyzeSemantics_FullMethodName  = "/academic.auditor.DocumentAuditor/AnalyzeSemantics"
	DocumentAuditor_InjectAnnotations_FullMethodName = "/academic.auditor.DocumentAuditor/InjectAnnotations"
)

// DocumentAuditorClient is the client API for DocumentAuditor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentAuditorClient interface {
	// 成员 A (Rust): 解析文档
	ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParsedData, error)
	// 成员 B (Java): 执行格式与规则审查
	AuditRules(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error)
	// 成员 C (Python): 语义与 AI 智能审查
	AnalyzeSemantics(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*AuditResponse, error)
	// 可选：写回批注后的文档
	InjectAnnotations(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error)
}

type documentAuditorClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentAuditorClient(cc grpc.ClientConnInterface) DocumentAuditorClient {
	return &documentAuditorClient{cc}
}

func (c *documentAuditorClient) ParseDocument(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParsedData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParsedData)
	err := c.cc.Invoke(ctx, DocumentAuditor_ParseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentAuditorClient) AuditRules(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, DocumentAuditor_AuditRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentAuditorClient) AnalyzeSemantics(ctx context.Context, in *SemanticRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, DocumentAuditor_AnalyzeSemantics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentAuditorClient) InjectAnnotations(ctx context.Context, in *InjectRequest, opts ...grpc.CallOption) (*InjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectResponse)
	err := c.cc.Invoke(ctx, DocumentAuditor_InjectAnnotations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentAuditorServer is the server API for DocumentAuditor service.
// All implementations must embed UnimplementedDocumentAuditorServer
// for forward compatibility.
type DocumentAuditorServer interface {
	// 成员 A (Rust): 解析文档
	ParseDocument(context.Context, *ParseRequest) (*ParsedData, error)
	// 成员 B (Java): 执行格式与规则审查
	AuditRules(context.Context, *AuditRequest) (*AuditResponse, error)
	// 成员 C (Python): 语义与 AI 智能审查
	AnalyzeSemantics(context.Context, *SemanticRequest) (*AuditResponse, error)
	// 可选：写回批注后的文档
	InjectAnnotations(context.Context, *InjectRequest) (*InjectResponse, error)
	mustEmbedUnimplementedDocumentAuditorServer()
}

// UnimplementedDocumentAuditorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentAuditorServer struct{}

func (UnimplementedDocumentAuditorServer) ParseDocument(context.Context, *ParseRequest) (*ParsedData, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedDocumentAuditorServer) AuditRules(context.Context, *AuditRequest) (*AuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditRules not implemented")
}
func (UnimplementedDocumentAuditorServer) AnalyzeSemantics(context.Context, *SemanticRequest) (*AuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeSemantics not implemented")
}
func (UnimplementedDocumentAuditorServer) InjectAnnotations(context.Context, *InjectRequest) (*InjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectAnnotations not implemented")
}
func (UnimplementedDocumentAuditorServer) mustEmbedUnimplementedDocumentAuditorServer() {}
func (UnimplementedDocumentAuditorServer) testEmbeddedByValue()                         {}

// UnsafeDocumentAuditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentAuditorServer will
// result in compilation errors.
type UnsafeDocumentAuditorServer interface {
	mustEmbedUnimplementedDocumentAuditorServer()
}

func RegisterDocumentAuditorServer(s grpc.ServiceRegistrar, srv DocumentAuditorServer) {
	// If the following call panics, it indicates UnimplementedDocumentAuditorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentAuditor_ServiceDesc, srv)
}

func _DocumentAuditor_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentAuditor_ParseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).ParseDocument(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentAuditor_AuditRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).AuditRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentAuditor_AuditRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).AuditRules(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentAuditor_AnalyzeSemantics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).AnalyzeSemantics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentAuditor_AnalyzeSemantics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).AnalyzeSemantics(ctx, req.(*SemanticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentAuditor_InjectAnnotations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentAuditorServer).InjectAnnotations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentAuditor_InjectAnnotations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentAuditorServer).InjectAnnotations(ctx, req.(*InjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentAuditor_ServiceDesc is the grpc.ServiceDesc for DocumentAuditor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentAuditor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "academic.auditor.DocumentAuditor",
	HandlerType: (*DocumentAuditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _DocumentAuditor_ParseDocument_Handler,
		},
		{
			MethodName: "AuditRules",
			Handler:    _DocumentAuditor_AuditRules_Handler,
		},
		{
			MethodName: "AnalyzeSemantics",
			Handler:    _DocumentAuditor_AnalyzeSemantics_Handler,
		},
		{
			MethodName: "InjectAnnotations",
			Handler:    _DocumentAuditor_InjectAnnotations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shared/protos/auditor.proto",
}
