// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

/**
 * Protobuf type {@code academic.auditor.AuditRequest}
 */
public final class AuditRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:academic.auditor.AuditRequest)
    AuditRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuditRequest.newBuilder() to construct.
  private AuditRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuditRequest() {
    targetRuleSet_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuditRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_AuditRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_AuditRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.auditor.grpc.AuditRequest.class, com.auditor.grpc.AuditRequest.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  private com.auditor.grpc.ParsedData data_;
  /**
   * <code>.academic.auditor.ParsedData data = 1;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.academic.auditor.ParsedData data = 1;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.auditor.grpc.ParsedData getData() {
    return data_ == null ? com.auditor.grpc.ParsedData.getDefaultInstance() : data_;
  }
  /**
   * <code>.academic.auditor.ParsedData data = 1;</code>
   */
  @java.lang.Override
  public com.auditor.grpc.ParsedDataOrBuilder getDataOrBuilder() {
    return data_ == null ? com.auditor.grpc.ParsedData.getDefaultInstance() : data_;
  }

  public static final int TARGET_RULE_SET_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object targetRuleSet_ = "";
  /**
   * <code>string target_rule_set = 2;</code>
   * @return The targetRuleSet.
   */
  @java.lang.Override
  public java.lang.String getTargetRuleSet() {
    java.lang.Object ref = targetRuleSet_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      targetRuleSet_ = s;
      return s;
    }
  }
  /**
   * <code>string target_rule_set = 2;</code>
   * @return The bytes for targetRuleSet.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetRuleSetBytes() {
    java.lang.Object ref = targetRuleSet_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      targetRuleSet_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (data_ != null) {
      output.writeMessage(1, getData());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetRuleSet_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, targetRuleSet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getData());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(targetRuleSet_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, targetRuleSet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.auditor.grpc.AuditRequest)) {
      return super.equals(obj);
    }
    com.auditor.grpc.AuditRequest other = (com.auditor.grpc.AuditRequest) obj;

    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getTargetRuleSet()
        .equals(other.getTargetRuleSet())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (37 * hash) + TARGET_RULE_SET_FIELD_NUMBER;
    hash = (53 * hash) + getTargetRuleSet().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.auditor.grpc.AuditRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.AuditRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.AuditRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.AuditRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.auditor.grpc.AuditRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code academic.auditor.AuditRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:academic.auditor.AuditRequest)
      com.auditor.grpc.AuditRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_AuditRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_AuditRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auditor.grpc.AuditRequest.class, com.auditor.grpc.AuditRequest.Builder.class);
    }

    // Construct using com.auditor.grpc.AuditRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      targetRuleSet_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_AuditRequest_descriptor;
    }

    @java.lang.Override
    public com.auditor.grpc.AuditRequest getDefaultInstanceForType() {
      return com.auditor.grpc.AuditRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.auditor.grpc.AuditRequest build() {
      com.auditor.grpc.AuditRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.auditor.grpc.AuditRequest buildPartial() {
      com.auditor.grpc.AuditRequest result = new com.auditor.grpc.AuditRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.auditor.grpc.AuditRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.targetRuleSet_ = targetRuleSet_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.auditor.grpc.AuditRequest) {
        return mergeFrom((com.auditor.grpc.AuditRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.auditor.grpc.AuditRequest other) {
      if (other == com.auditor.grpc.AuditRequest.getDefaultInstance()) return this;
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (!other.getTargetRuleSet().isEmpty()) {
        targetRuleSet_ = other.targetRuleSet_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              targetRuleSet_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.auditor.grpc.ParsedData data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.auditor.grpc.ParsedData, com.auditor.grpc.ParsedData.Builder, com.auditor.grpc.ParsedDataOrBuilder> dataBuilder_;
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     * @return The data.
     */
    public com.auditor.grpc.ParsedData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.auditor.grpc.ParsedData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    public Builder setData(com.auditor.grpc.ParsedData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    public Builder setData(
        com.auditor.grpc.ParsedData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    public Builder mergeData(com.auditor.grpc.ParsedData value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          data_ != null &&
          data_ != com.auditor.grpc.ParsedData.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000001);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    public com.auditor.grpc.ParsedData.Builder getDataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    public com.auditor.grpc.ParsedDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.auditor.grpc.ParsedData.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.academic.auditor.ParsedData data = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.auditor.grpc.ParsedData, com.auditor.grpc.ParsedData.Builder, com.auditor.grpc.ParsedDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.auditor.grpc.ParsedData, com.auditor.grpc.ParsedData.Builder, com.auditor.grpc.ParsedDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private java.lang.Object targetRuleSet_ = "";
    /**
     * <code>string target_rule_set = 2;</code>
     * @return The targetRuleSet.
     */
    public java.lang.String getTargetRuleSet() {
      java.lang.Object ref = targetRuleSet_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetRuleSet_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target_rule_set = 2;</code>
     * @return The bytes for targetRuleSet.
     */
    public com.google.protobuf.ByteString
        getTargetRuleSetBytes() {
      java.lang.Object ref = targetRuleSet_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetRuleSet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target_rule_set = 2;</code>
     * @param value The targetRuleSet to set.
     * @return This builder for chaining.
     */
    public Builder setTargetRuleSet(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      targetRuleSet_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string target_rule_set = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTargetRuleSet() {
      targetRuleSet_ = getDefaultInstance().getTargetRuleSet();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string target_rule_set = 2;</code>
     * @param value The bytes for targetRuleSet to set.
     * @return This builder for chaining.
     */
    public Builder setTargetRuleSetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      targetRuleSet_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:academic.auditor.AuditRequest)
  }

  // @@protoc_insertion_point(class_scope:academic.auditor.AuditRequest)
  private static final com.auditor.grpc.AuditRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.auditor.grpc.AuditRequest();
  }

  public static com.auditor.grpc.AuditRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuditRequest>
      PARSER = new com.google.protobuf.AbstractParser<AuditRequest>() {
    @java.lang.Override
    public AuditRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuditRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuditRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.auditor.grpc.AuditRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

