// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface AuditResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.AuditResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .academic.auditor.Issue issues = 1;</code>
   */
  java.util.List<com.auditor.grpc.Issue> 
      getIssuesList();
  /**
   * <code>repeated .academic.auditor.Issue issues = 1;</code>
   */
  com.auditor.grpc.Issue getIssues(int index);
  /**
   * <code>repeated .academic.auditor.Issue issues = 1;</code>
   */
  int getIssuesCount();
  /**
   * <code>repeated .academic.auditor.Issue issues = 1;</code>
   */
  java.util.List<? extends com.auditor.grpc.IssueOrBuilder> 
      getIssuesOrBuilderList();
  /**
   * <code>repeated .academic.auditor.Issue issues = 1;</code>
   */
  com.auditor.grpc.IssueOrBuilder getIssuesOrBuilder(
      int index);

  /**
   * <pre>
   * 该模块发现的扣分项总计
   * </pre>
   *
   * <code>float score_impact = 2;</code>
   * @return The scoreImpact.
   */
  float getScoreImpact();
}
