// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public final class AuditorProto {
  private AuditorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_ParseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_ParseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_ParsedData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_ParsedData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_DocumentMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_DocumentMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_Section_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_Section_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_Section_PropsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_Section_PropsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_Reference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_Reference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_AuditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_AuditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_SemanticRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_SemanticRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_AuditResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_AuditResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_academic_auditor_Issue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_academic_auditor_Issue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rauditor.proto\022\020academic.auditor\"8\n\014Par" +
      "seRequest\022\021\n\tfile_path\030\001 \001(\t\022\025\n\rtemplate" +
      "_type\030\002 \001(\t\"\260\001\n\nParsedData\022\016\n\006doc_id\030\001 \001" +
      "(\t\0224\n\010metadata\030\002 \001(\0132\".academic.auditor." +
      "DocumentMetadata\022+\n\010sections\030\003 \003(\0132\031.aca" +
      "demic.auditor.Section\022/\n\nreferences\030\004 \003(" +
      "\0132\033.academic.auditor.Reference\"`\n\020Docume" +
      "ntMetadata\022\r\n\005title\030\001 \001(\t\022\022\n\npage_count\030" +
      "\002 \001(\005\022\022\n\nmargin_top\030\003 \001(\002\022\025\n\rmargin_bott" +
      "om\030\004 \001(\002\"\253\001\n\007Section\022\022\n\nsection_id\030\001 \001(\005" +
      "\022\014\n\004type\030\002 \001(\t\022\r\n\005level\030\003 \001(\005\022\014\n\004text\030\004 " +
      "\001(\t\0223\n\005props\030\005 \003(\0132$.academic.auditor.Se" +
      "ction.PropsEntry\032,\n\nPropsEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"F\n\tReference\022\016\n\006r" +
      "ef_id\030\001 \001(\t\022\020\n\010raw_text\030\002 \001(\t\022\027\n\017is_vali" +
      "d_format\030\003 \001(\010\"S\n\014AuditRequest\022*\n\004data\030\001" +
      " \001(\0132\034.academic.auditor.ParsedData\022\027\n\017ta" +
      "rget_rule_set\030\002 \001(\t\"U\n\017SemanticRequest\022+" +
      "\n\010sections\030\001 \003(\0132\031.academic.auditor.Sect" +
      "ion\022\025\n\rmodel_version\030\002 \001(\t\"N\n\rAuditRespo" +
      "nse\022\'\n\006issues\030\001 \003(\0132\027.academic.auditor.I" +
      "ssue\022\024\n\014score_impact\030\002 \001(\002\"\226\001\n\005Issue\022\014\n\004" +
      "code\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\022\n\nsection_i" +
      "d\030\003 \001(\005\022,\n\010severity\030\004 \001(\0162\032.academic.aud" +
      "itor.Severity\022\022\n\nsuggestion\030\005 \001(\t\022\030\n\020ori" +
      "ginal_snippet\030\006 \001(\t*A\n\010Severity\022\010\n\004INFO\020" +
      "\000\022\007\n\003LOW\020\001\022\n\n\006MEDIUM\020\002\022\010\n\004HIGH\020\003\022\014\n\010CRIT" +
      "ICAL\020\0042\207\002\n\017DocumentAuditor\022M\n\rParseDocum" +
      "ent\022\036.academic.auditor.ParseRequest\032\034.ac" +
      "ademic.auditor.ParsedData\022M\n\nAuditRules\022" +
      "\036.academic.auditor.AuditRequest\032\037.academ" +
      "ic.auditor.AuditResponse\022V\n\020AnalyzeSeman" +
      "tics\022!.academic.auditor.SemanticRequest\032" +
      "\037.academic.auditor.AuditResponseB\"\n\020com." +
      "auditor.grpcB\014AuditorProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_academic_auditor_ParseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_academic_auditor_ParseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_ParseRequest_descriptor,
        new java.lang.String[] { "FilePath", "TemplateType", });
    internal_static_academic_auditor_ParsedData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_academic_auditor_ParsedData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_ParsedData_descriptor,
        new java.lang.String[] { "DocId", "Metadata", "Sections", "References", });
    internal_static_academic_auditor_DocumentMetadata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_academic_auditor_DocumentMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_DocumentMetadata_descriptor,
        new java.lang.String[] { "Title", "PageCount", "MarginTop", "MarginBottom", });
    internal_static_academic_auditor_Section_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_academic_auditor_Section_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_Section_descriptor,
        new java.lang.String[] { "SectionId", "Type", "Level", "Text", "Props", });
    internal_static_academic_auditor_Section_PropsEntry_descriptor =
      internal_static_academic_auditor_Section_descriptor.getNestedTypes().get(0);
    internal_static_academic_auditor_Section_PropsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_Section_PropsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_academic_auditor_Reference_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_academic_auditor_Reference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_Reference_descriptor,
        new java.lang.String[] { "RefId", "RawText", "IsValidFormat", });
    internal_static_academic_auditor_AuditRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_academic_auditor_AuditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_AuditRequest_descriptor,
        new java.lang.String[] { "Data", "TargetRuleSet", });
    internal_static_academic_auditor_SemanticRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_academic_auditor_SemanticRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_SemanticRequest_descriptor,
        new java.lang.String[] { "Sections", "ModelVersion", });
    internal_static_academic_auditor_AuditResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_academic_auditor_AuditResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_AuditResponse_descriptor,
        new java.lang.String[] { "Issues", "ScoreImpact", });
    internal_static_academic_auditor_Issue_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_academic_auditor_Issue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_academic_auditor_Issue_descriptor,
        new java.lang.String[] { "Code", "Message", "SectionId", "Severity", "Suggestion", "OriginalSnippet", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
