// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface AuditRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.AuditRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.academic.auditor.ParsedData data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.academic.auditor.ParsedData data = 1;</code>
   * @return The data.
   */
  com.auditor.grpc.ParsedData getData();
  /**
   * <code>.academic.auditor.ParsedData data = 1;</code>
   */
  com.auditor.grpc.ParsedDataOrBuilder getDataOrBuilder();

  /**
   * <code>string target_rule_set = 2;</code>
   * @return The targetRuleSet.
   */
  java.lang.String getTargetRuleSet();
  /**
   * <code>string target_rule_set = 2;</code>
   * @return The bytes for targetRuleSet.
   */
  com.google.protobuf.ByteString
      getTargetRuleSetBytes();
}
