// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface DocumentMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.DocumentMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int32 page_count = 2;</code>
   * @return The pageCount.
   */
  int getPageCount();

  /**
   * <code>float margin_top = 3;</code>
   * @return The marginTop.
   */
  float getMarginTop();

  /**
   * <code>float margin_bottom = 4;</code>
   * @return The marginBottom.
   */
  float getMarginBottom();
}
