// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface IssueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.Issue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 错误代码，如 "ERR_FONT_001"
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * 错误代码，如 "ERR_FONT_001"
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <pre>
   * 给用户的错误描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 给用户的错误描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 关联的段落 ID
   * </pre>
   *
   * <code>int32 section_id = 3;</code>
   * @return The sectionId.
   */
  int getSectionId();

  /**
   * <code>.academic.auditor.Severity severity = 4;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.academic.auditor.Severity severity = 4;</code>
   * @return The severity.
   */
  com.auditor.grpc.Severity getSeverity();

  /**
   * <pre>
   * 修改建议
   * </pre>
   *
   * <code>string suggestion = 5;</code>
   * @return The suggestion.
   */
  java.lang.String getSuggestion();
  /**
   * <pre>
   * 修改建议
   * </pre>
   *
   * <code>string suggestion = 5;</code>
   * @return The bytes for suggestion.
   */
  com.google.protobuf.ByteString
      getSuggestionBytes();

  /**
   * <pre>
   * 原始错误文本片段
   * </pre>
   *
   * <code>string original_snippet = 6;</code>
   * @return The originalSnippet.
   */
  java.lang.String getOriginalSnippet();
  /**
   * <pre>
   * 原始错误文本片段
   * </pre>
   *
   * <code>string original_snippet = 6;</code>
   * @return The bytes for originalSnippet.
   */
  com.google.protobuf.ByteString
      getOriginalSnippetBytes();
}
