// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

/**
 * Protobuf type {@code academic.auditor.Issue}
 */
public final class Issue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:academic.auditor.Issue)
    IssueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Issue.newBuilder() to construct.
  private Issue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Issue() {
    code_ = "";
    message_ = "";
    severity_ = 0;
    suggestion_ = "";
    originalSnippet_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Issue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Issue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Issue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.auditor.grpc.Issue.class, com.auditor.grpc.Issue.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object code_ = "";
  /**
   * <pre>
   * 错误代码，如 "ERR_FONT_001"
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public java.lang.String getCode() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      code_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 错误代码，如 "ERR_FONT_001"
   * </pre>
   *
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCodeBytes() {
    java.lang.Object ref = code_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      code_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <pre>
   * 给用户的错误描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 给用户的错误描述
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECTION_ID_FIELD_NUMBER = 3;
  private int sectionId_ = 0;
  /**
   * <pre>
   * 关联的段落 ID
   * </pre>
   *
   * <code>int32 section_id = 3;</code>
   * @return The sectionId.
   */
  @java.lang.Override
  public int getSectionId() {
    return sectionId_;
  }

  public static final int SEVERITY_FIELD_NUMBER = 4;
  private int severity_ = 0;
  /**
   * <code>.academic.auditor.Severity severity = 4;</code>
   * @return The enum numeric value on the wire for severity.
   */
  @java.lang.Override public int getSeverityValue() {
    return severity_;
  }
  /**
   * <code>.academic.auditor.Severity severity = 4;</code>
   * @return The severity.
   */
  @java.lang.Override public com.auditor.grpc.Severity getSeverity() {
    com.auditor.grpc.Severity result = com.auditor.grpc.Severity.forNumber(severity_);
    return result == null ? com.auditor.grpc.Severity.UNRECOGNIZED : result;
  }

  public static final int SUGGESTION_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object suggestion_ = "";
  /**
   * <pre>
   * 修改建议
   * </pre>
   *
   * <code>string suggestion = 5;</code>
   * @return The suggestion.
   */
  @java.lang.Override
  public java.lang.String getSuggestion() {
    java.lang.Object ref = suggestion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      suggestion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 修改建议
   * </pre>
   *
   * <code>string suggestion = 5;</code>
   * @return The bytes for suggestion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSuggestionBytes() {
    java.lang.Object ref = suggestion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      suggestion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_SNIPPET_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalSnippet_ = "";
  /**
   * <pre>
   * 原始错误文本片段
   * </pre>
   *
   * <code>string original_snippet = 6;</code>
   * @return The originalSnippet.
   */
  @java.lang.Override
  public java.lang.String getOriginalSnippet() {
    java.lang.Object ref = originalSnippet_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalSnippet_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始错误文本片段
   * </pre>
   *
   * <code>string original_snippet = 6;</code>
   * @return The bytes for originalSnippet.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalSnippetBytes() {
    java.lang.Object ref = originalSnippet_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalSnippet_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (sectionId_ != 0) {
      output.writeInt32(3, sectionId_);
    }
    if (severity_ != com.auditor.grpc.Severity.INFO.getNumber()) {
      output.writeEnum(4, severity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(suggestion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, suggestion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalSnippet_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, originalSnippet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (sectionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, sectionId_);
    }
    if (severity_ != com.auditor.grpc.Severity.INFO.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, severity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(suggestion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, suggestion_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalSnippet_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, originalSnippet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.auditor.grpc.Issue)) {
      return super.equals(obj);
    }
    com.auditor.grpc.Issue other = (com.auditor.grpc.Issue) obj;

    if (!getCode()
        .equals(other.getCode())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getSectionId()
        != other.getSectionId()) return false;
    if (severity_ != other.severity_) return false;
    if (!getSuggestion()
        .equals(other.getSuggestion())) return false;
    if (!getOriginalSnippet()
        .equals(other.getOriginalSnippet())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + SECTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSectionId();
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + severity_;
    hash = (37 * hash) + SUGGESTION_FIELD_NUMBER;
    hash = (53 * hash) + getSuggestion().hashCode();
    hash = (37 * hash) + ORIGINAL_SNIPPET_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalSnippet().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.auditor.grpc.Issue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.Issue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.Issue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.Issue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.Issue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.Issue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.Issue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.Issue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.Issue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.Issue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.Issue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.Issue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.auditor.grpc.Issue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code academic.auditor.Issue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:academic.auditor.Issue)
      com.auditor.grpc.IssueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Issue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Issue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auditor.grpc.Issue.class, com.auditor.grpc.Issue.Builder.class);
    }

    // Construct using com.auditor.grpc.Issue.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = "";
      message_ = "";
      sectionId_ = 0;
      severity_ = 0;
      suggestion_ = "";
      originalSnippet_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Issue_descriptor;
    }

    @java.lang.Override
    public com.auditor.grpc.Issue getDefaultInstanceForType() {
      return com.auditor.grpc.Issue.getDefaultInstance();
    }

    @java.lang.Override
    public com.auditor.grpc.Issue build() {
      com.auditor.grpc.Issue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.auditor.grpc.Issue buildPartial() {
      com.auditor.grpc.Issue result = new com.auditor.grpc.Issue(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.auditor.grpc.Issue result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sectionId_ = sectionId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.severity_ = severity_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.suggestion_ = suggestion_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.originalSnippet_ = originalSnippet_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.auditor.grpc.Issue) {
        return mergeFrom((com.auditor.grpc.Issue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.auditor.grpc.Issue other) {
      if (other == com.auditor.grpc.Issue.getDefaultInstance()) return this;
      if (!other.getCode().isEmpty()) {
        code_ = other.code_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getSectionId() != 0) {
        setSectionId(other.getSectionId());
      }
      if (other.severity_ != 0) {
        setSeverityValue(other.getSeverityValue());
      }
      if (!other.getSuggestion().isEmpty()) {
        suggestion_ = other.suggestion_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getOriginalSnippet().isEmpty()) {
        originalSnippet_ = other.originalSnippet_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              code_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              sectionId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              severity_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              suggestion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              originalSnippet_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object code_ = "";
    /**
     * <pre>
     * 错误代码，如 "ERR_FONT_001"
     * </pre>
     *
     * <code>string code = 1;</code>
     * @return The code.
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 错误代码，如 "ERR_FONT_001"
     * </pre>
     *
     * <code>string code = 1;</code>
     * @return The bytes for code.
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 错误代码，如 "ERR_FONT_001"
     * </pre>
     *
     * <code>string code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误代码，如 "ERR_FONT_001"
     * </pre>
     *
     * <code>string code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      code_ = getDefaultInstance().getCode();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 错误代码，如 "ERR_FONT_001"
     * </pre>
     *
     * <code>string code = 1;</code>
     * @param value The bytes for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * 给用户的错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 给用户的错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 给用户的错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 给用户的错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 给用户的错误描述
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int sectionId_ ;
    /**
     * <pre>
     * 关联的段落 ID
     * </pre>
     *
     * <code>int32 section_id = 3;</code>
     * @return The sectionId.
     */
    @java.lang.Override
    public int getSectionId() {
      return sectionId_;
    }
    /**
     * <pre>
     * 关联的段落 ID
     * </pre>
     *
     * <code>int32 section_id = 3;</code>
     * @param value The sectionId to set.
     * @return This builder for chaining.
     */
    public Builder setSectionId(int value) {
      
      sectionId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 关联的段落 ID
     * </pre>
     *
     * <code>int32 section_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSectionId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sectionId_ = 0;
      onChanged();
      return this;
    }

    private int severity_ = 0;
    /**
     * <code>.academic.auditor.Severity severity = 4;</code>
     * @return The enum numeric value on the wire for severity.
     */
    @java.lang.Override public int getSeverityValue() {
      return severity_;
    }
    /**
     * <code>.academic.auditor.Severity severity = 4;</code>
     * @param value The enum numeric value on the wire for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityValue(int value) {
      severity_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.Severity severity = 4;</code>
     * @return The severity.
     */
    @java.lang.Override
    public com.auditor.grpc.Severity getSeverity() {
      com.auditor.grpc.Severity result = com.auditor.grpc.Severity.forNumber(severity_);
      return result == null ? com.auditor.grpc.Severity.UNRECOGNIZED : result;
    }
    /**
     * <code>.academic.auditor.Severity severity = 4;</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(com.auditor.grpc.Severity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      severity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.Severity severity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      severity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object suggestion_ = "";
    /**
     * <pre>
     * 修改建议
     * </pre>
     *
     * <code>string suggestion = 5;</code>
     * @return The suggestion.
     */
    public java.lang.String getSuggestion() {
      java.lang.Object ref = suggestion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        suggestion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 修改建议
     * </pre>
     *
     * <code>string suggestion = 5;</code>
     * @return The bytes for suggestion.
     */
    public com.google.protobuf.ByteString
        getSuggestionBytes() {
      java.lang.Object ref = suggestion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        suggestion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 修改建议
     * </pre>
     *
     * <code>string suggestion = 5;</code>
     * @param value The suggestion to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      suggestion_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改建议
     * </pre>
     *
     * <code>string suggestion = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuggestion() {
      suggestion_ = getDefaultInstance().getSuggestion();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 修改建议
     * </pre>
     *
     * <code>string suggestion = 5;</code>
     * @param value The bytes for suggestion to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      suggestion_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object originalSnippet_ = "";
    /**
     * <pre>
     * 原始错误文本片段
     * </pre>
     *
     * <code>string original_snippet = 6;</code>
     * @return The originalSnippet.
     */
    public java.lang.String getOriginalSnippet() {
      java.lang.Object ref = originalSnippet_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalSnippet_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始错误文本片段
     * </pre>
     *
     * <code>string original_snippet = 6;</code>
     * @return The bytes for originalSnippet.
     */
    public com.google.protobuf.ByteString
        getOriginalSnippetBytes() {
      java.lang.Object ref = originalSnippet_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalSnippet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始错误文本片段
     * </pre>
     *
     * <code>string original_snippet = 6;</code>
     * @param value The originalSnippet to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalSnippet(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalSnippet_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始错误文本片段
     * </pre>
     *
     * <code>string original_snippet = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalSnippet() {
      originalSnippet_ = getDefaultInstance().getOriginalSnippet();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始错误文本片段
     * </pre>
     *
     * <code>string original_snippet = 6;</code>
     * @param value The bytes for originalSnippet to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalSnippetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originalSnippet_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:academic.auditor.Issue)
  }

  // @@protoc_insertion_point(class_scope:academic.auditor.Issue)
  private static final com.auditor.grpc.Issue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.auditor.grpc.Issue();
  }

  public static com.auditor.grpc.Issue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Issue>
      PARSER = new com.google.protobuf.AbstractParser<Issue>() {
    @java.lang.Override
    public Issue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Issue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Issue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.auditor.grpc.Issue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

