// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface ParsedDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.ParsedData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doc_id = 1;</code>
   * @return The docId.
   */
  java.lang.String getDocId();
  /**
   * <code>string doc_id = 1;</code>
   * @return The bytes for docId.
   */
  com.google.protobuf.ByteString
      getDocIdBytes();

  /**
   * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
   * @return The metadata.
   */
  com.auditor.grpc.DocumentMetadata getMetadata();
  /**
   * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
   */
  com.auditor.grpc.DocumentMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  java.util.List<com.auditor.grpc.Section> 
      getSectionsList();
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  com.auditor.grpc.Section getSections(int index);
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  int getSectionsCount();
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  java.util.List<? extends com.auditor.grpc.SectionOrBuilder> 
      getSectionsOrBuilderList();
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  com.auditor.grpc.SectionOrBuilder getSectionsOrBuilder(
      int index);

  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  java.util.List<com.auditor.grpc.Reference> 
      getReferencesList();
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  com.auditor.grpc.Reference getReferences(int index);
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  int getReferencesCount();
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  java.util.List<? extends com.auditor.grpc.ReferenceOrBuilder> 
      getReferencesOrBuilderList();
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  com.auditor.grpc.ReferenceOrBuilder getReferencesOrBuilder(
      int index);
}
