// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface ParseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.ParseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 文档在共享存储中的路径
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <pre>
   * 文档在共享存储中的路径
   * </pre>
   *
   * <code>string file_path = 1;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();

  /**
   * <pre>
   * 例如: "GB/T7714", "APA"
   * </pre>
   *
   * <code>string template_type = 2;</code>
   * @return The templateType.
   */
  java.lang.String getTemplateType();
  /**
   * <pre>
   * 例如: "GB/T7714", "APA"
   * </pre>
   *
   * <code>string template_type = 2;</code>
   * @return The bytes for templateType.
   */
  com.google.protobuf.ByteString
      getTemplateTypeBytes();
}
