// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

/**
 * Protobuf type {@code academic.auditor.ParsedData}
 */
public final class ParsedData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:academic.auditor.ParsedData)
    ParsedDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ParsedData.newBuilder() to construct.
  private ParsedData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ParsedData() {
    docId_ = "";
    sections_ = java.util.Collections.emptyList();
    references_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ParsedData();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_ParsedData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_ParsedData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.auditor.grpc.ParsedData.class, com.auditor.grpc.ParsedData.Builder.class);
  }

  public static final int DOC_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object docId_ = "";
  /**
   * <code>string doc_id = 1;</code>
   * @return The docId.
   */
  @java.lang.Override
  public java.lang.String getDocId() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      docId_ = s;
      return s;
    }
  }
  /**
   * <code>string doc_id = 1;</code>
   * @return The bytes for docId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDocIdBytes() {
    java.lang.Object ref = docId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      docId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 2;
  private com.auditor.grpc.DocumentMetadata metadata_;
  /**
   * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.auditor.grpc.DocumentMetadata getMetadata() {
    return metadata_ == null ? com.auditor.grpc.DocumentMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
   */
  @java.lang.Override
  public com.auditor.grpc.DocumentMetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.auditor.grpc.DocumentMetadata.getDefaultInstance() : metadata_;
  }

  public static final int SECTIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.auditor.grpc.Section> sections_;
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.auditor.grpc.Section> getSectionsList() {
    return sections_;
  }
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.auditor.grpc.SectionOrBuilder> 
      getSectionsOrBuilderList() {
    return sections_;
  }
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  @java.lang.Override
  public int getSectionsCount() {
    return sections_.size();
  }
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  @java.lang.Override
  public com.auditor.grpc.Section getSections(int index) {
    return sections_.get(index);
  }
  /**
   * <code>repeated .academic.auditor.Section sections = 3;</code>
   */
  @java.lang.Override
  public com.auditor.grpc.SectionOrBuilder getSectionsOrBuilder(
      int index) {
    return sections_.get(index);
  }

  public static final int REFERENCES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.auditor.grpc.Reference> references_;
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.auditor.grpc.Reference> getReferencesList() {
    return references_;
  }
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.auditor.grpc.ReferenceOrBuilder> 
      getReferencesOrBuilderList() {
    return references_;
  }
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  @java.lang.Override
  public int getReferencesCount() {
    return references_.size();
  }
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  @java.lang.Override
  public com.auditor.grpc.Reference getReferences(int index) {
    return references_.get(index);
  }
  /**
   * <code>repeated .academic.auditor.Reference references = 4;</code>
   */
  @java.lang.Override
  public com.auditor.grpc.ReferenceOrBuilder getReferencesOrBuilder(
      int index) {
    return references_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(docId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, docId_);
    }
    if (metadata_ != null) {
      output.writeMessage(2, getMetadata());
    }
    for (int i = 0; i < sections_.size(); i++) {
      output.writeMessage(3, sections_.get(i));
    }
    for (int i = 0; i < references_.size(); i++) {
      output.writeMessage(4, references_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(docId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, docId_);
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetadata());
    }
    for (int i = 0; i < sections_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, sections_.get(i));
    }
    for (int i = 0; i < references_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, references_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.auditor.grpc.ParsedData)) {
      return super.equals(obj);
    }
    com.auditor.grpc.ParsedData other = (com.auditor.grpc.ParsedData) obj;

    if (!getDocId()
        .equals(other.getDocId())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getSectionsList()
        .equals(other.getSectionsList())) return false;
    if (!getReferencesList()
        .equals(other.getReferencesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDocId().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    if (getSectionsCount() > 0) {
      hash = (37 * hash) + SECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getSectionsList().hashCode();
    }
    if (getReferencesCount() > 0) {
      hash = (37 * hash) + REFERENCES_FIELD_NUMBER;
      hash = (53 * hash) + getReferencesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.auditor.grpc.ParsedData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.ParsedData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.ParsedData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.ParsedData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.ParsedData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.ParsedData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.auditor.grpc.ParsedData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code academic.auditor.ParsedData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:academic.auditor.ParsedData)
      com.auditor.grpc.ParsedDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_ParsedData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_ParsedData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auditor.grpc.ParsedData.class, com.auditor.grpc.ParsedData.Builder.class);
    }

    // Construct using com.auditor.grpc.ParsedData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      docId_ = "";
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      if (sectionsBuilder_ == null) {
        sections_ = java.util.Collections.emptyList();
      } else {
        sections_ = null;
        sectionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (referencesBuilder_ == null) {
        references_ = java.util.Collections.emptyList();
      } else {
        references_ = null;
        referencesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_ParsedData_descriptor;
    }

    @java.lang.Override
    public com.auditor.grpc.ParsedData getDefaultInstanceForType() {
      return com.auditor.grpc.ParsedData.getDefaultInstance();
    }

    @java.lang.Override
    public com.auditor.grpc.ParsedData build() {
      com.auditor.grpc.ParsedData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.auditor.grpc.ParsedData buildPartial() {
      com.auditor.grpc.ParsedData result = new com.auditor.grpc.ParsedData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.auditor.grpc.ParsedData result) {
      if (sectionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          sections_ = java.util.Collections.unmodifiableList(sections_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.sections_ = sections_;
      } else {
        result.sections_ = sectionsBuilder_.build();
      }
      if (referencesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          references_ = java.util.Collections.unmodifiableList(references_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.references_ = references_;
      } else {
        result.references_ = referencesBuilder_.build();
      }
    }

    private void buildPartial0(com.auditor.grpc.ParsedData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.docId_ = docId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.auditor.grpc.ParsedData) {
        return mergeFrom((com.auditor.grpc.ParsedData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.auditor.grpc.ParsedData other) {
      if (other == com.auditor.grpc.ParsedData.getDefaultInstance()) return this;
      if (!other.getDocId().isEmpty()) {
        docId_ = other.docId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (sectionsBuilder_ == null) {
        if (!other.sections_.isEmpty()) {
          if (sections_.isEmpty()) {
            sections_ = other.sections_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSectionsIsMutable();
            sections_.addAll(other.sections_);
          }
          onChanged();
        }
      } else {
        if (!other.sections_.isEmpty()) {
          if (sectionsBuilder_.isEmpty()) {
            sectionsBuilder_.dispose();
            sectionsBuilder_ = null;
            sections_ = other.sections_;
            bitField0_ = (bitField0_ & ~0x00000004);
            sectionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSectionsFieldBuilder() : null;
          } else {
            sectionsBuilder_.addAllMessages(other.sections_);
          }
        }
      }
      if (referencesBuilder_ == null) {
        if (!other.references_.isEmpty()) {
          if (references_.isEmpty()) {
            references_ = other.references_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureReferencesIsMutable();
            references_.addAll(other.references_);
          }
          onChanged();
        }
      } else {
        if (!other.references_.isEmpty()) {
          if (referencesBuilder_.isEmpty()) {
            referencesBuilder_.dispose();
            referencesBuilder_ = null;
            references_ = other.references_;
            bitField0_ = (bitField0_ & ~0x00000008);
            referencesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getReferencesFieldBuilder() : null;
          } else {
            referencesBuilder_.addAllMessages(other.references_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              docId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.auditor.grpc.Section m =
                  input.readMessage(
                      com.auditor.grpc.Section.parser(),
                      extensionRegistry);
              if (sectionsBuilder_ == null) {
                ensureSectionsIsMutable();
                sections_.add(m);
              } else {
                sectionsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.auditor.grpc.Reference m =
                  input.readMessage(
                      com.auditor.grpc.Reference.parser(),
                      extensionRegistry);
              if (referencesBuilder_ == null) {
                ensureReferencesIsMutable();
                references_.add(m);
              } else {
                referencesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object docId_ = "";
    /**
     * <code>string doc_id = 1;</code>
     * @return The docId.
     */
    public java.lang.String getDocId() {
      java.lang.Object ref = docId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        docId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string doc_id = 1;</code>
     * @return The bytes for docId.
     */
    public com.google.protobuf.ByteString
        getDocIdBytes() {
      java.lang.Object ref = docId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        docId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string doc_id = 1;</code>
     * @param value The docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      docId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string doc_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocId() {
      docId_ = getDefaultInstance().getDocId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string doc_id = 1;</code>
     * @param value The bytes for docId to set.
     * @return This builder for chaining.
     */
    public Builder setDocIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      docId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.auditor.grpc.DocumentMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.auditor.grpc.DocumentMetadata, com.auditor.grpc.DocumentMetadata.Builder, com.auditor.grpc.DocumentMetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     * @return The metadata.
     */
    public com.auditor.grpc.DocumentMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.auditor.grpc.DocumentMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    public Builder setMetadata(com.auditor.grpc.DocumentMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    public Builder setMetadata(
        com.auditor.grpc.DocumentMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    public Builder mergeMetadata(com.auditor.grpc.DocumentMetadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          metadata_ != null &&
          metadata_ != com.auditor.grpc.DocumentMetadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000002);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    public com.auditor.grpc.DocumentMetadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    public com.auditor.grpc.DocumentMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.auditor.grpc.DocumentMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.academic.auditor.DocumentMetadata metadata = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.auditor.grpc.DocumentMetadata, com.auditor.grpc.DocumentMetadata.Builder, com.auditor.grpc.DocumentMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.auditor.grpc.DocumentMetadata, com.auditor.grpc.DocumentMetadata.Builder, com.auditor.grpc.DocumentMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private java.util.List<com.auditor.grpc.Section> sections_ =
      java.util.Collections.emptyList();
    private void ensureSectionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        sections_ = new java.util.ArrayList<com.auditor.grpc.Section>(sections_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.auditor.grpc.Section, com.auditor.grpc.Section.Builder, com.auditor.grpc.SectionOrBuilder> sectionsBuilder_;

    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public java.util.List<com.auditor.grpc.Section> getSectionsList() {
      if (sectionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sections_);
      } else {
        return sectionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public int getSectionsCount() {
      if (sectionsBuilder_ == null) {
        return sections_.size();
      } else {
        return sectionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public com.auditor.grpc.Section getSections(int index) {
      if (sectionsBuilder_ == null) {
        return sections_.get(index);
      } else {
        return sectionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder setSections(
        int index, com.auditor.grpc.Section value) {
      if (sectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSectionsIsMutable();
        sections_.set(index, value);
        onChanged();
      } else {
        sectionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder setSections(
        int index, com.auditor.grpc.Section.Builder builderForValue) {
      if (sectionsBuilder_ == null) {
        ensureSectionsIsMutable();
        sections_.set(index, builderForValue.build());
        onChanged();
      } else {
        sectionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder addSections(com.auditor.grpc.Section value) {
      if (sectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSectionsIsMutable();
        sections_.add(value);
        onChanged();
      } else {
        sectionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder addSections(
        int index, com.auditor.grpc.Section value) {
      if (sectionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSectionsIsMutable();
        sections_.add(index, value);
        onChanged();
      } else {
        sectionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder addSections(
        com.auditor.grpc.Section.Builder builderForValue) {
      if (sectionsBuilder_ == null) {
        ensureSectionsIsMutable();
        sections_.add(builderForValue.build());
        onChanged();
      } else {
        sectionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder addSections(
        int index, com.auditor.grpc.Section.Builder builderForValue) {
      if (sectionsBuilder_ == null) {
        ensureSectionsIsMutable();
        sections_.add(index, builderForValue.build());
        onChanged();
      } else {
        sectionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder addAllSections(
        java.lang.Iterable<? extends com.auditor.grpc.Section> values) {
      if (sectionsBuilder_ == null) {
        ensureSectionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sections_);
        onChanged();
      } else {
        sectionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder clearSections() {
      if (sectionsBuilder_ == null) {
        sections_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        sectionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public Builder removeSections(int index) {
      if (sectionsBuilder_ == null) {
        ensureSectionsIsMutable();
        sections_.remove(index);
        onChanged();
      } else {
        sectionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public com.auditor.grpc.Section.Builder getSectionsBuilder(
        int index) {
      return getSectionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public com.auditor.grpc.SectionOrBuilder getSectionsOrBuilder(
        int index) {
      if (sectionsBuilder_ == null) {
        return sections_.get(index);  } else {
        return sectionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public java.util.List<? extends com.auditor.grpc.SectionOrBuilder> 
         getSectionsOrBuilderList() {
      if (sectionsBuilder_ != null) {
        return sectionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sections_);
      }
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public com.auditor.grpc.Section.Builder addSectionsBuilder() {
      return getSectionsFieldBuilder().addBuilder(
          com.auditor.grpc.Section.getDefaultInstance());
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public com.auditor.grpc.Section.Builder addSectionsBuilder(
        int index) {
      return getSectionsFieldBuilder().addBuilder(
          index, com.auditor.grpc.Section.getDefaultInstance());
    }
    /**
     * <code>repeated .academic.auditor.Section sections = 3;</code>
     */
    public java.util.List<com.auditor.grpc.Section.Builder> 
         getSectionsBuilderList() {
      return getSectionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.auditor.grpc.Section, com.auditor.grpc.Section.Builder, com.auditor.grpc.SectionOrBuilder> 
        getSectionsFieldBuilder() {
      if (sectionsBuilder_ == null) {
        sectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.auditor.grpc.Section, com.auditor.grpc.Section.Builder, com.auditor.grpc.SectionOrBuilder>(
                sections_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        sections_ = null;
      }
      return sectionsBuilder_;
    }

    private java.util.List<com.auditor.grpc.Reference> references_ =
      java.util.Collections.emptyList();
    private void ensureReferencesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        references_ = new java.util.ArrayList<com.auditor.grpc.Reference>(references_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.auditor.grpc.Reference, com.auditor.grpc.Reference.Builder, com.auditor.grpc.ReferenceOrBuilder> referencesBuilder_;

    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public java.util.List<com.auditor.grpc.Reference> getReferencesList() {
      if (referencesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(references_);
      } else {
        return referencesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public int getReferencesCount() {
      if (referencesBuilder_ == null) {
        return references_.size();
      } else {
        return referencesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public com.auditor.grpc.Reference getReferences(int index) {
      if (referencesBuilder_ == null) {
        return references_.get(index);
      } else {
        return referencesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder setReferences(
        int index, com.auditor.grpc.Reference value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReferencesIsMutable();
        references_.set(index, value);
        onChanged();
      } else {
        referencesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder setReferences(
        int index, com.auditor.grpc.Reference.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.set(index, builderForValue.build());
        onChanged();
      } else {
        referencesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder addReferences(com.auditor.grpc.Reference value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReferencesIsMutable();
        references_.add(value);
        onChanged();
      } else {
        referencesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder addReferences(
        int index, com.auditor.grpc.Reference value) {
      if (referencesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureReferencesIsMutable();
        references_.add(index, value);
        onChanged();
      } else {
        referencesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder addReferences(
        com.auditor.grpc.Reference.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.add(builderForValue.build());
        onChanged();
      } else {
        referencesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder addReferences(
        int index, com.auditor.grpc.Reference.Builder builderForValue) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.add(index, builderForValue.build());
        onChanged();
      } else {
        referencesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder addAllReferences(
        java.lang.Iterable<? extends com.auditor.grpc.Reference> values) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, references_);
        onChanged();
      } else {
        referencesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder clearReferences() {
      if (referencesBuilder_ == null) {
        references_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        referencesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public Builder removeReferences(int index) {
      if (referencesBuilder_ == null) {
        ensureReferencesIsMutable();
        references_.remove(index);
        onChanged();
      } else {
        referencesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public com.auditor.grpc.Reference.Builder getReferencesBuilder(
        int index) {
      return getReferencesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public com.auditor.grpc.ReferenceOrBuilder getReferencesOrBuilder(
        int index) {
      if (referencesBuilder_ == null) {
        return references_.get(index);  } else {
        return referencesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public java.util.List<? extends com.auditor.grpc.ReferenceOrBuilder> 
         getReferencesOrBuilderList() {
      if (referencesBuilder_ != null) {
        return referencesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(references_);
      }
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public com.auditor.grpc.Reference.Builder addReferencesBuilder() {
      return getReferencesFieldBuilder().addBuilder(
          com.auditor.grpc.Reference.getDefaultInstance());
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public com.auditor.grpc.Reference.Builder addReferencesBuilder(
        int index) {
      return getReferencesFieldBuilder().addBuilder(
          index, com.auditor.grpc.Reference.getDefaultInstance());
    }
    /**
     * <code>repeated .academic.auditor.Reference references = 4;</code>
     */
    public java.util.List<com.auditor.grpc.Reference.Builder> 
         getReferencesBuilderList() {
      return getReferencesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.auditor.grpc.Reference, com.auditor.grpc.Reference.Builder, com.auditor.grpc.ReferenceOrBuilder> 
        getReferencesFieldBuilder() {
      if (referencesBuilder_ == null) {
        referencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.auditor.grpc.Reference, com.auditor.grpc.Reference.Builder, com.auditor.grpc.ReferenceOrBuilder>(
                references_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        references_ = null;
      }
      return referencesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:academic.auditor.ParsedData)
  }

  // @@protoc_insertion_point(class_scope:academic.auditor.ParsedData)
  private static final com.auditor.grpc.ParsedData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.auditor.grpc.ParsedData();
  }

  public static com.auditor.grpc.ParsedData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParsedData>
      PARSER = new com.google.protobuf.AbstractParser<ParsedData>() {
    @java.lang.Override
    public ParsedData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParsedData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParsedData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.auditor.grpc.ParsedData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

