// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

/**
 * Protobuf type {@code academic.auditor.Reference}
 */
public final class Reference extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:academic.auditor.Reference)
    ReferenceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Reference.newBuilder() to construct.
  private Reference(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Reference() {
    refId_ = "";
    rawText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Reference();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Reference_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Reference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.auditor.grpc.Reference.class, com.auditor.grpc.Reference.Builder.class);
  }

  public static final int REF_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object refId_ = "";
  /**
   * <pre>
   * 例如 "[1]"
   * </pre>
   *
   * <code>string ref_id = 1;</code>
   * @return The refId.
   */
  @java.lang.Override
  public java.lang.String getRefId() {
    java.lang.Object ref = refId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 例如 "[1]"
   * </pre>
   *
   * <code>string ref_id = 1;</code>
   * @return The bytes for refId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefIdBytes() {
    java.lang.Object ref = refId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RAW_TEXT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rawText_ = "";
  /**
   * <code>string raw_text = 2;</code>
   * @return The rawText.
   */
  @java.lang.Override
  public java.lang.String getRawText() {
    java.lang.Object ref = rawText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rawText_ = s;
      return s;
    }
  }
  /**
   * <code>string raw_text = 2;</code>
   * @return The bytes for rawText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRawTextBytes() {
    java.lang.Object ref = rawText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rawText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_VALID_FORMAT_FIELD_NUMBER = 3;
  private boolean isValidFormat_ = false;
  /**
   * <code>bool is_valid_format = 3;</code>
   * @return The isValidFormat.
   */
  @java.lang.Override
  public boolean getIsValidFormat() {
    return isValidFormat_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(refId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, refId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rawText_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rawText_);
    }
    if (isValidFormat_ != false) {
      output.writeBool(3, isValidFormat_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(refId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, refId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rawText_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rawText_);
    }
    if (isValidFormat_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isValidFormat_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.auditor.grpc.Reference)) {
      return super.equals(obj);
    }
    com.auditor.grpc.Reference other = (com.auditor.grpc.Reference) obj;

    if (!getRefId()
        .equals(other.getRefId())) return false;
    if (!getRawText()
        .equals(other.getRawText())) return false;
    if (getIsValidFormat()
        != other.getIsValidFormat()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REF_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRefId().hashCode();
    hash = (37 * hash) + RAW_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getRawText().hashCode();
    hash = (37 * hash) + IS_VALID_FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsValidFormat());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.auditor.grpc.Reference parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.Reference parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.Reference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.Reference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.Reference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.auditor.grpc.Reference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.auditor.grpc.Reference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.Reference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.Reference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.Reference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.auditor.grpc.Reference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.auditor.grpc.Reference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.auditor.grpc.Reference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code academic.auditor.Reference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:academic.auditor.Reference)
      com.auditor.grpc.ReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Reference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Reference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.auditor.grpc.Reference.class, com.auditor.grpc.Reference.Builder.class);
    }

    // Construct using com.auditor.grpc.Reference.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      refId_ = "";
      rawText_ = "";
      isValidFormat_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.auditor.grpc.AuditorProto.internal_static_academic_auditor_Reference_descriptor;
    }

    @java.lang.Override
    public com.auditor.grpc.Reference getDefaultInstanceForType() {
      return com.auditor.grpc.Reference.getDefaultInstance();
    }

    @java.lang.Override
    public com.auditor.grpc.Reference build() {
      com.auditor.grpc.Reference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.auditor.grpc.Reference buildPartial() {
      com.auditor.grpc.Reference result = new com.auditor.grpc.Reference(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.auditor.grpc.Reference result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.refId_ = refId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rawText_ = rawText_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isValidFormat_ = isValidFormat_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.auditor.grpc.Reference) {
        return mergeFrom((com.auditor.grpc.Reference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.auditor.grpc.Reference other) {
      if (other == com.auditor.grpc.Reference.getDefaultInstance()) return this;
      if (!other.getRefId().isEmpty()) {
        refId_ = other.refId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRawText().isEmpty()) {
        rawText_ = other.rawText_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getIsValidFormat() != false) {
        setIsValidFormat(other.getIsValidFormat());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              refId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              rawText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              isValidFormat_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object refId_ = "";
    /**
     * <pre>
     * 例如 "[1]"
     * </pre>
     *
     * <code>string ref_id = 1;</code>
     * @return The refId.
     */
    public java.lang.String getRefId() {
      java.lang.Object ref = refId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 例如 "[1]"
     * </pre>
     *
     * <code>string ref_id = 1;</code>
     * @return The bytes for refId.
     */
    public com.google.protobuf.ByteString
        getRefIdBytes() {
      java.lang.Object ref = refId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 例如 "[1]"
     * </pre>
     *
     * <code>string ref_id = 1;</code>
     * @param value The refId to set.
     * @return This builder for chaining.
     */
    public Builder setRefId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      refId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 例如 "[1]"
     * </pre>
     *
     * <code>string ref_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefId() {
      refId_ = getDefaultInstance().getRefId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 例如 "[1]"
     * </pre>
     *
     * <code>string ref_id = 1;</code>
     * @param value The bytes for refId to set.
     * @return This builder for chaining.
     */
    public Builder setRefIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      refId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object rawText_ = "";
    /**
     * <code>string raw_text = 2;</code>
     * @return The rawText.
     */
    public java.lang.String getRawText() {
      java.lang.Object ref = rawText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rawText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string raw_text = 2;</code>
     * @return The bytes for rawText.
     */
    public com.google.protobuf.ByteString
        getRawTextBytes() {
      java.lang.Object ref = rawText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rawText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string raw_text = 2;</code>
     * @param value The rawText to set.
     * @return This builder for chaining.
     */
    public Builder setRawText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rawText_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string raw_text = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRawText() {
      rawText_ = getDefaultInstance().getRawText();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string raw_text = 2;</code>
     * @param value The bytes for rawText to set.
     * @return This builder for chaining.
     */
    public Builder setRawTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rawText_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean isValidFormat_ ;
    /**
     * <code>bool is_valid_format = 3;</code>
     * @return The isValidFormat.
     */
    @java.lang.Override
    public boolean getIsValidFormat() {
      return isValidFormat_;
    }
    /**
     * <code>bool is_valid_format = 3;</code>
     * @param value The isValidFormat to set.
     * @return This builder for chaining.
     */
    public Builder setIsValidFormat(boolean value) {
      
      isValidFormat_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_valid_format = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsValidFormat() {
      bitField0_ = (bitField0_ & ~0x00000004);
      isValidFormat_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:academic.auditor.Reference)
  }

  // @@protoc_insertion_point(class_scope:academic.auditor.Reference)
  private static final com.auditor.grpc.Reference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.auditor.grpc.Reference();
  }

  public static com.auditor.grpc.Reference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reference>
      PARSER = new com.google.protobuf.AbstractParser<Reference>() {
    @java.lang.Override
    public Reference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Reference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reference> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.auditor.grpc.Reference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

