// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface ReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.Reference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 例如 "[1]"
   * </pre>
   *
   * <code>string ref_id = 1;</code>
   * @return The refId.
   */
  java.lang.String getRefId();
  /**
   * <pre>
   * 例如 "[1]"
   * </pre>
   *
   * <code>string ref_id = 1;</code>
   * @return The bytes for refId.
   */
  com.google.protobuf.ByteString
      getRefIdBytes();

  /**
   * <code>string raw_text = 2;</code>
   * @return The rawText.
   */
  java.lang.String getRawText();
  /**
   * <code>string raw_text = 2;</code>
   * @return The bytes for rawText.
   */
  com.google.protobuf.ByteString
      getRawTextBytes();

  /**
   * <code>bool is_valid_format = 3;</code>
   * @return The isValidFormat.
   */
  boolean getIsValidFormat();
}
