// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface SectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.Section)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 section_id = 1;</code>
   * @return The sectionId.
   */
  int getSectionId();

  /**
   * <pre>
   * "heading", "paragraph", "table", "figure"
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * "heading", "paragraph", "table", "figure"
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * 标题层级，0为正文
   * </pre>
   *
   * <code>int32 level = 3;</code>
   * @return The level.
   */
  int getLevel();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   * {"font": "SimSun", "size": "12pt", "indent": "2"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; props = 5;</code>
   */
  int getPropsCount();
  /**
   * <pre>
   * {"font": "SimSun", "size": "12pt", "indent": "2"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; props = 5;</code>
   */
  boolean containsProps(
      java.lang.String key);
  /**
   * Use {@link #getPropsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProps();
  /**
   * <pre>
   * {"font": "SimSun", "size": "12pt", "indent": "2"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; props = 5;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropsMap();
  /**
   * <pre>
   * {"font": "SimSun", "size": "12pt", "indent": "2"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; props = 5;</code>
   */
  /* nullable */
java.lang.String getPropsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * {"font": "SimSun", "size": "12pt", "indent": "2"}
   * </pre>
   *
   * <code>map&lt;string, string&gt; props = 5;</code>
   */
  java.lang.String getPropsOrThrow(
      java.lang.String key);
}
