// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

public interface SemanticRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:academic.auditor.SemanticRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .academic.auditor.Section sections = 1;</code>
   */
  java.util.List<com.auditor.grpc.Section> 
      getSectionsList();
  /**
   * <code>repeated .academic.auditor.Section sections = 1;</code>
   */
  com.auditor.grpc.Section getSections(int index);
  /**
   * <code>repeated .academic.auditor.Section sections = 1;</code>
   */
  int getSectionsCount();
  /**
   * <code>repeated .academic.auditor.Section sections = 1;</code>
   */
  java.util.List<? extends com.auditor.grpc.SectionOrBuilder> 
      getSectionsOrBuilderList();
  /**
   * <code>repeated .academic.auditor.Section sections = 1;</code>
   */
  com.auditor.grpc.SectionOrBuilder getSectionsOrBuilder(
      int index);

  /**
   * <pre>
   * 例如 "qwen-2.5-72b"
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The modelVersion.
   */
  java.lang.String getModelVersion();
  /**
   * <pre>
   * 例如 "qwen-2.5-72b"
   * </pre>
   *
   * <code>string model_version = 2;</code>
   * @return The bytes for modelVersion.
   */
  com.google.protobuf.ByteString
      getModelVersionBytes();
}
