// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auditor.proto

package com.auditor.grpc;

/**
 * Protobuf enum {@code academic.auditor.Severity}
 */
public enum Severity
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INFO = 0;</code>
   */
  INFO(0),
  /**
   * <code>LOW = 1;</code>
   */
  LOW(1),
  /**
   * <code>MEDIUM = 2;</code>
   */
  MEDIUM(2),
  /**
   * <code>HIGH = 3;</code>
   */
  HIGH(3),
  /**
   * <code>CRITICAL = 4;</code>
   */
  CRITICAL(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INFO = 0;</code>
   */
  public static final int INFO_VALUE = 0;
  /**
   * <code>LOW = 1;</code>
   */
  public static final int LOW_VALUE = 1;
  /**
   * <code>MEDIUM = 2;</code>
   */
  public static final int MEDIUM_VALUE = 2;
  /**
   * <code>HIGH = 3;</code>
   */
  public static final int HIGH_VALUE = 3;
  /**
   * <code>CRITICAL = 4;</code>
   */
  public static final int CRITICAL_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Severity valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Severity forNumber(int value) {
    switch (value) {
      case 0: return INFO;
      case 1: return LOW;
      case 2: return MEDIUM;
      case 3: return HIGH;
      case 4: return CRITICAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Severity>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Severity> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Severity>() {
          public Severity findValueByNumber(int number) {
            return Severity.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.auditor.grpc.AuditorProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final Severity[] VALUES = values();

  public static Severity valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Severity(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:academic.auditor.Severity)
}

